add test

diff --git a/.github/workflows/terraform-test.yaml b/.github/workflows/terraform-test.yaml
--- a/.github/workflows/terraform-test.yaml
+++ b/.github/workflows/terraform-test.yaml
@@ -45,8 +45,14 @@ jobs:
       - name: Curl to ArgoCD
         run: curl localhost:8080
 
-      - name: Get pods in argocd-apps namespace
-        run: kubectl get po -n argocd-apps
+      - name: Check number of pods in argocd-apps namespace
+        run: |
+          POD_NUM=`kubectl get po -n argocd-apps | grep guestbook | wc -l`
+          if [ $POD_NUM -ne 1 ]; then
+            echo "Invalid pod number. The test application may not be deployed."
+            exit 1
+          fi
+
 
       - name: Terraform destroy
         run: terraform destroy -auto-approve
